In [43]:
import scipy.io as scio
import torch as t
def reader_breast():
    data = scio.loadmat('datasets/breast.mat')['breast'].toarray()
    features, targets = t.Tensor(data[:, :-1]), t.Tensor(data[:, -1])
    targets = t.where(targets != 1, t.zeros_like(targets), targets)
    return features, targets

In [44]:
reader_breast()

(tensor([[-0.8576,  0.5556,  1.0000,  ...,  0.7778,  0.3333, -1.0000],
         [-0.8539, -0.1111, -0.5556,  ..., -0.3333, -0.3333, -1.0000],
         [-0.8535,  0.5556,  0.3333,  ..., -0.1111, -0.1111, -0.3333],
         ...,
         [-0.8955, -0.5556, -1.0000,  ..., -0.7778, -1.0000, -0.7778],
         [-0.8935, -0.5556, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
         [-0.8837, -0.7778, -1.0000,  ..., -1.0000, -1.0000, -1.0000]]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [79]:
def reader_australian():
    data = scio.loadmat('datasets/Australian.mat')
    features, targets = data['fea'], data['gnd']
    features, targets = t.Tensor(features.toarray()), t.Tensor(targets).squeeze()
    targets = t.where(targets != 1, t.zeros_like(targets), targets)
    return features, targets

In [106]:
import os
import ssl
import torch
import pandas as pd
import urllib.request
from ucimlrepo import fetch_ucirepo
os.environ['http_proxy'] = '127.0.0.1:1066'
os.environ['https_proxy'] = '127.0.0.1:1066'

ssl._create_default_https_context = ssl._create_unverified_context

def _preprocess_data(uci_id):
        # fetch dataset
        dataset = fetch_ucirepo(id=uci_id)
        
        # data (as pandas dataframes)
        X = dataset.data.features
        y = dataset.data.targets
        
        # 检测并删除缺失值
        combined = pd.concat([X, y], axis=1)
        combined_cleaned = combined.dropna()

        # 分离 features 和 targets
        X_cleaned = combined_cleaned.iloc[:, :-1]
        y_cleaned = combined_cleaned.iloc[:, -1]

        # 转换为 PyTorch 张量
        features = torch.Tensor(X_cleaned.to_numpy())
        targets = torch.Tensor(y_cleaned.to_numpy()).flatten()

        return features, targets

def get_uci_dataset_by_id(uci_id):

    match int(uci_id):
        case 15:
            # Breast
            features, targets = _preprocess_data(uci_id)
            targets = torch.where(targets != 4, torch.tensor(0.), torch.tensor(1.)) # 4为恶性 2为良性 改为1,0
            print(f'{features.shape}, p:{torch.sum(targets).item()}, n:{torch.sum(targets != 1).item()}')
            return features, targets
        case 143:
            # Australian
            features, targets = _preprocess_data(uci_id)
            targets = torch.where(targets != 1, torch.tensor(0.), torch.tensor(1.)) # 1 为正类 2为负 改为1,0
            print(f'{features.shape}, p:{torch.sum(targets).item()}, n:{torch.sum(targets != 1).item()}')
            return features, targets
        case 267:
            # banknote
            features, targets = _preprocess_data(uci_id)
            targets = torch.where(targets != 1, torch.tensor(0.), torch.tensor(1.)) # 1 为正类 2为负 改为1,0
            print(f'{features.shape}, p:{torch.sum(targets).item()}, n:{torch.sum(targets != 1).item()}')
            return features, targets
        case 171:
            # Madelon
            pass
        case 327:
            # Phishing
            features, targets = _preprocess_data(uci_id)
            targets = torch.where(targets != 1, torch.tensor(0.), torch.tensor(1.)) # 1 为正类 2为负 改为1,0
            print(f'{features.shape}, p:{torch.sum(targets).item()}, n:{torch.sum(targets != 1).item()}')
            return features, targets
        case 105:
            # Vote
            features, targets = _preprocess_data(uci_id)
            targets = torch.where(targets != 1, torch.tensor(0.), torch.tensor(1.)) # 1 为正类 2为负 改为1,0
            print(f'{features.shape}, p:{torch.sum(targets).item()}, n:{torch.sum(targets != 1).item()}')
            return features, targets
        case _:
            # 所有不需要特殊处理的都可以直接转换
            features, targets = _preprocess_data(uci_id)
            targets = torch.where(targets != 1, torch.tensor(0.), torch.tensor(1.)) # 改为1,0 
            print(f'{features.shape}, p:{torch.sum(targets).item()}, n:{torch.sum(targets != 1).item()}')
            return features, targets
            
        
        
            


In [111]:
features,targets = get_uci_dataset_by_id(15)

torch.Size([683, 9]), p:239.0, n:444


In [112]:
features

tensor([[ 5.,  1.,  1.,  ...,  3.,  1.,  1.],
        [ 5.,  4.,  4.,  ...,  3.,  2.,  1.],
        [ 3.,  1.,  1.,  ...,  3.,  1.,  1.],
        ...,
        [ 5., 10., 10.,  ...,  8., 10.,  2.],
        [ 4.,  8.,  6.,  ..., 10.,  6.,  1.],
        [ 4.,  8.,  8.,  ..., 10.,  4.,  1.]])

In [110]:
targets

tensor([0., 0., 0.,  ..., 0., 0., 0.])